### ISSUE TITLE
Symptom reports screen

### ISSUE THREAD

**Issue by i-schuetz** [Co-Epi/app-android#136]
Just happened to run the new UI, some issues:

- The button shadows are missing https://www.figma.com/file/W488uiXhnllYTkMcsBvAcX/CoEpi?node-id=21628%3A30070
- The submit button should have round corners.
- The buttons feel a bit too close together and/or small. Can imagine people mis-tapping them (more if sick).
- It should not be possible to select "No symptoms" and any of the other buttons at the same time.
- The vector background is missing. I think we can reuse the one from the thanks screen.
- Do we want to keep the green notification with "Symptoms submitted"? Probably it's redundant now?
- The buttons/items should have probably ripple effect (this is standard, but maybe confirm with UX).

<img width="308" alt="Screen Shot 2020-05-05 at 15 55 10" src="https://user-images.githubusercontent.com/1381744/81074977-083e1800-8eea-11ea-92e1-d83cea94c58f.png">

**Comment by yibter** [comment]
Light/dark backgrounds resolved in... #137

**Comment by yibter** [comment]
Added button style with drop-shadows in... #140

**Comment by yibter** [comment]
Symptom button spacing (& drop shadows) added in.. #140

**Comment by yibter** [comment]
Rounded corners (and drop shadow) added via issue #141
