### ISSUE TITLE
New UX - date since earliest symptoms screen

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-android#153]
Goal: we want to add a screen where, at the end of the symptom workflow (after any severity workflow is done), to ask users what the earliest day of the symptom onset was?

Use same design as the 'how many days of cough'/fever screen, but we'll adjust the text depending on whether there is a single symptom submitted, or multiple. 

![image](https://user-images.githubusercontent.com/7468165/81732211-02de5180-9445-11ea-8592-e6008207549d.png)

**Comment by i-schuetz** [comment]
See PR.
