### ISSUE TITLE
Current Develop Build Failing

### ISSUE THREAD

**Issue by Joshua-McCord** [Co-Epi/app-android#154]
**Describe the bug**
On the BreathlessViewModel, there appears to be a Type Mismatch error in the onSelected function 

**To Reproduce**
1. Try to build
2. Failure, and error should be in BreathlessViewModel (ui->symptoms->breathless)

**Additional context**
Current Development build of app-android is failing, this should be the cause of the crash

**Comment by yibter** [comment]
Looks like there was a bad merge. Just pushed a PR https://github.com/Co-Epi/app-android/pull/155
