### ISSUE TITLE
Explore Rust integration

### ISSUE THREAD

**Issue by yibter** [Co-Epi/app-android#174]
Integrate the App Backend Rust project...
https://github.com/Co-Epi/app-backend-rust

Mimic the iOS Rust Integration as much as possible...
https://github.com/Co-Epi/app-ios/tree/feature/rust-integration

Adding Native Code to Android...
https://developer.android.com/studio/projects/add-native-code

Cargo NDK for building Android libs...
https://docs.rs/crate/cargo-ndk/0.2.0

Older, but pretty good example from Mozilla using Rust in Android...
https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html

Interesting decentralized native package dependency manager
https://github.com/google/cdep

Native Dependencies in Android Studio 4.0 (beta)
https://android-developers.googleblog.com/2020/02/native-dependencies-in-android-studio-40.html

**Comment by yibter** [comment]
Mostly exploring what the latest and greatest tools/patterns we can use. I did get the Mozilla example working where data was being passed between a Rust lib and Android app I created. Next step is to use the app-backend-rust lib and the Co-Ep android app. Then move on to package management.

**Comment by yibter** [comment]
Quick update on this issue. Just created a branch where I'm passing & receiving strings with the rust lib called app-backend-rust. And here’s our rust lib with the JNI calls and scripts to build & link the libs… https://github.com/Co-Epi/app-backend-rust/tree/feature/android. Currently, the rust calls aren’t wired into the right spot yet in the Android app and a good chunk of the rust lib has been disabled due to an openssl build dependency issue I was running into.  So those are the next items to resolve.

**Comment by ivnsch** [comment]
I'm setting the milestone to 0.4 (it was implied to be 0.3) because i think that it's better to test in stages, first only iOS. We already have a working Android implementation for 0.3 so there's not a good reason to switch right now.
