### ISSUE TITLE
New UX - exposure alert screen(s)

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-android#180]
![image](https://user-images.githubusercontent.com/7468165/82512279-7414a900-9ac4-11ea-8a0a-d6a4d5f3d247.png)

see figma for details.

**Comment by mellowgeek** [comment]
@danamlewis just to clarify, the save button on the exposure alert detail screen doesn't need to be implemented until we are persisting things locally, after v0.3, is that correct?
