### ISSUE TITLE
Port FFI Unit Tests from iOS

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-android#190]
We added functionality to Rust to support struct and callbacks in FFI, for iOS: https://github.com/Co-Epi/app-backend-rust/blob/master/src/ios/ffi_for_sanity_tests.rs

Specifically:
- Passing struct to Rust as a parameter.
- Receiving struct from Rust as return value.
- Passing callback as a parameter.
- Passing callback and triggering it.

These are the corresponding Unit Tests in the iOS app:
https://github.com/Co-Epi/app-ios/commit/5832b0cf15ab91dea2038d9d662d0fbbe9a0f4fa

One the JNI interface is ready ([issue](https://github.com/Co-Epi/app-backend-rust/issues/32)), port the Unit Tests to Android.

@yibter you can do the [Rust issue](https://github.com/Co-Epi/app-backend-rust/issues/32) too, if you want.

Edit: I'd add the current string/JSON experiment to these tests.

**Comment by yibter** [comment]
Oh nice @i-schuetz ! I'll give it a shot tonight. Thanks!
