### ISSUE TITLE
Provide a build for FDroid

### ISSUE THREAD

**Issue by pravi** [Co-Epi/app-android#191]
**Is your feature request related to a problem? Please describe.**
I don't use Google Play Store and instead use FDroid for Free Software only apps. I'd like to test this app, but cannot do it currently.

**Describe the solution you'd like**
You should publish this app on https://f-droid.org/

**Describe alternatives you've considered**
Or a less elegant option would be provide a direct apk download.

**Additional context**
F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.

**Comment by danamlewis** [comment]
Thanks! We're planning to provide an APK to use once we have our next testing version ready.
