### ISSUE TITLE
Reports match only for the first TCN matched

### ISSUE THREAD

**Issue by mellowgeek** [Co-Epi/app-android#196]
Using the swipe-delete-exposure branch and build 39 from app center on two devices,Samsung Galaxy S9 and a Pixel 3 XL respectively. Attempting to simulate multiple contact exposures for one phone by clearing the app data on the second device to simulate a second contact.

**To Reproduce**
Starting with fresh installs on both devices:
1. Check debug to make sure both devices observe the TCN of the other device.
2. On one phone, submit a symptom report twice, to account for an existing TCN bug. This device will be the one simulating two devices
3. On the other phone, open the Exposure Alert screen and pull to refresh. Check the debug logs for updated matching logs. A new match should occur and be added to the alerts. Returning to the Exposure Alert screen will show the new alert. It is possible to get 2 matches in this case.
4. On the first phone, open the app info screen and clear the data for the phone. Open the app again and go through all the prompts.
5. On the second phone, check to make sure the phone recognizes the new TCN of the first phone in the debug logs.
6. Repeat steps 2 and 3.
7. Return to the exposure alert screen, the new exposure alerts are not added.

**Expected behavior**
New exposure alerts should show up after the first phone's data is cleared and a new symptom report is submitted.

**Comment by haleybear** [comment]
I have been stepping through this process with @mellowgeek and attached are the logs.
Pulled the most recent version to two devices:

- Pixel3 - Android 10
- Pixel3XL - Android 10

[Pixel3-ExposureAlert.txt](https://github.com/Co-Epi/app-android/files/4738137/Pixel3-ExposureAlert.txt)

[Pixel3XL-SymptomReport.txt](https://github.com/Co-Epi/app-android/files/4738138/Pixel3XL-SymptomReport.txt)

**Comment by ivnsch** [comment]
Can you test again with current develop please? Haven't tried to reproduce it yet, but there are 2 changes that affect this:
- The bug with the first report not generating TCNs / matching should be fixed now.
- Removed an operator in the alerts flow that was preventing them from being displayed (sometimes?).

Edit: Another change that affects this: https://github.com/Co-Epi/app-android/pull/209

**Comment by haleybear** [comment]
> Can you test again with current develop please? Haven't tried to reproduce it yet, but there are 2 changes that affect this:
> 
> * The bug with the first report not generating TCNs / matching should be fixed now.
> * Removed an operator in the alerts flow that was preventing them from being displayed (sometimes?).

I pulled the new code down, uninstalled the app on both phones, and tried to load the new version. 

The Pixel3 loaded it, but the Pixel3XL is getting the below error repeatedly.

I power-cycled the phone, unplugged the physical cable, and toggled the USB debugging option within Settings; however, the error still occurs when trying to load this onto the Pixel3XL.



```06/05 20:31:38: Launching 'app' on Google Pixel 3 XL.
$ adb shell am start -n "org.coepi.android/org.coepi.android.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "org.coepi.android/org.coepi.android.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.coepi.android/.MainActivity }
Error type 3
Error: Activity class {org.coepi.android/org.coepi.android.MainActivity} does not exist.

Error while Launching activity

**Comment by ivnsch** [comment]
@haleybear Try cleaning the project, restarting Android Studio etc. See e.g. [SO post](https://stackoverflow.com/a/24241687/930450). This is unrelated with this app. If you continue experiencing it, please open a new issue, since it's unrelated with this one.

**Comment by haleybear** [comment]
@i-schuetz @mellowgeek 
Found my issue (I was running multiple users for testing) and re-worked with the newest version. I didn't have to leave the screen for the exposure notifications to update this time. 
Attached are the logs. 

[Pixel3XL-Symptom-Reporting.txt](https://github.com/Co-Epi/app-android/files/4748444/Pixel3XL-Symptom-Reporting.txt)

[Pixel3-Exposure-Alerts.txt](https://github.com/Co-Epi/app-android/files/4748445/Pixel3-Exposure-Alerts.txt)

**Comment by ivnsch** [comment]
@haleybear not quite sure I understand, is it working now?

**Comment by haleybear** [comment]
> @haleybear not quite sure I understand, is it working now?

Yes. It appears to be working now.

**Comment by ivnsch** [comment]
Good news! @mellowgeek can you please test if the bug you described is still happening?

**Comment by mellowgeek** [comment]
@i-schuetz looks like that bug is gone! Closing this. Thanks!
