### ISSUE TITLE
Graceful handling of incorrectly formatted backend response

### ISSUE THREAD

**Issue by LookItsJosh** [Co-Epi/app-android#204]
The app crashes if it receives an incorrectly formatted (non-base64 encoded) response from the backend. App should gracefully handle any corrupt or unexpected API responses without crashing

**Comment by ivnsch** [comment]
Hmm, strange. The app handles decoding failure. Will try to reproduce it tomorrow.

**Comment by ivnsch** [comment]
I just tested this and the app didn't crash. Can you provide more details (like what string is causing it, api level, etc)?
![Screenshot_1591428967](https://user-images.githubusercontent.com/1381744/83938986-791e6b80-a7d9-11ea-9880-4e30df443a0b.png)

**Comment by LookItsJosh** [comment]
I see, a colleague brought the bug up to me. His specific wording is:

"if the posted string isn’t a BASE64 encoded array of numbers, the front-end will crash when it retrieves those values back from the back-end."

I'll ask if he's got more details/using an older build of the app or something.

**Comment by LookItsJosh** [comment]
He says "If the base64 encoded string does represent an array of numbers — for example, if it represents JSON instead — then when the app retrieves that report and tries to parse it, it will hang the application."

**Comment by i-schuetz** [comment]
JSON array of numbers: `[1, 2, 3]`

Didn't crash: 
> Couldn't decode string with Base64: [1, 2, 3], api: 29

Can you provide more details?

**Comment by ivnsch** [comment]
Ok, I was able to find it. It crashes when the base64 decoding is successful, but the TCN library doesn't find the expected format. Will handle it.

**Comment by ivnsch** [comment]
Thanks for the report!
