### ISSUE TITLE
Exposure Alert: Overlapping Views during Transition

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-android#226]
**Describe the bug**
Currently the Exposure Alert Detail screen overlaps with the Exposure Alert Screen and looks as though the application is lagging. 

**To Reproduce**
1. Submit symptoms on a device
2. On a receiving device navigate to the Exposure Alert view and drag to update
3. Select the available symptom (which navigates to the Exposure Alert detail view)
4. Select the back arrow to navigate back to the main Exposure Alert screen
5. Observe that the text overlaps the main Exposure Alert screen briefly

**Expected behavior**
We expect that transitions are clean and do not have both views overlapping.

**Screenshots**
![Exposure-alert-transition](https://user-images.githubusercontent.com/36253327/84297727-0506ff00-ab1c-11ea-93de-c11e4f20bcb4.png)

**Additional context**
Phone: Pixel3 
Android Version: 10
Branch Versions: [Here](https://github.com/Co-Epi/app-android/tree/afdeb567fd91c085b09c4758f3e2d9aa9d3671ed)
[Exposure Alert Transition.txt](https://github.com/Co-Epi/app-android/files/4760137/Exposure.Alert.Transition.txt)

**Comment by ivnsch** [comment]
This is a cross fade animation. It seems to be too slow. But we will clarify first with the designers what transitions they want.

**Comment by ivnsch** [comment]
I'll remove the transitions for now.
