### ISSUE TITLE
Test Rust setup

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-android#238]
Someone who hasn't configured the Rust library for Android yet:

Clone Rust repo:
https://github.com/Co-Epi/app-backend-rust

Checkout Android branch with Rust integration:
https://github.com/Co-Epi/app-android/tree/app-backend-rust

Follow these instructions to wire the Rust lib:
https://github.com/Co-Epi/app-backend-rust/wiki/Building-library-for-Android

Run `FFISanityTests` in the Android app, on an emulator and at least one device.

Document issues found (if any)

**Comment by mellowgeek** [comment]
Went through steps on MacOS 10.15.5, `FFISanityTests` passed on Galaxy S9, but failed in the emulator.

**Comment by ivnsch** [comment]
@mellowgeek Can you describe how ?

**Comment by mellowgeek** [comment]
@i-schuetz 3 of 8 tests failed, [here are the error logs](https://gist.github.com/mellowgeek/f86a521f9a5a0f82c10a6ac746112490).

"couldn't find "libcoepi_core.so""

**Comment by ivnsch** [comment]
Is your emulator 64 bits (x86_64)?

**Comment by mellowgeek** [comment]
nope, that explains it.

**Comment by ivnsch** [comment]
Can you update core and try again with x86?

**Comment by mellowgeek** [comment]
Pulled the latest on app-backend-rust, but I'm getting errors related to code in src/ios when running the create android script.

**Comment by laurenipsum365** [comment]
I came across issues when testing on a Windows environment (as I mentioned in slack). There seems to be an issue with the sym linking and creating the native jniLibs directories.

**Comment by ivnsch** [comment]
@mellowgeek it should be fixed now. Let me know if it works.

@laurenipsum365 right, we haven't thought about Windows yet. Let's wait for the integration of core as external dependency (https://github.com/Co-Epi/app-backend-rust/issues/66). We may have to remove the symlinks.

**Comment by mellowgeek** [comment]
@i-schuetz build is working again, all tests passed on x86 android
