### ISSUE TITLE
Bluetooth pop-up request missing information

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-android#239]
**Describe the bug**
Currently if the user has BT off after initial installation the application has an alert dialog "CoEpi wants to turn on Bluetooth" with options to Deny or Allow. The need for this is not clear or included in the popup, which goes against the "Tenets of working with Android permissions" in that it is not clear why the user needs to give access to BT. Selecting Deny clears the view without any further explanation of how the app will be diminished. 
Even though the BT permissions are generally tied to the GPS location permissions it is still necessary to clarify why BT needs to be enabled in this alert dialog.

**To Reproduce**
1. Install application
2. Accept Location permissions
3. Turn off Bluetooth on phone
4. See alert dialog

**Expected behavior**
An alert dialog is displayed still at step 4, but has additional information.
"CoEpi wants to turn on Bluetooth:
_Brief explanation of how BT is used in this app and how the app will be different if the user denies access._
Deny Allow"

**Screenshots**
![Bluetooth-Request](https://user-images.githubusercontent.com/36253327/84780664-d5407700-afb3-11ea-8617-e83bfe317ed5.png)

**Additional context**
Phone: Pixel 3
OS: Android 10
App Version: https://github.com/Co-Epi/app-android/tree/559e0a273b5eade24436d12e9044b27f6bcb4222

**Comment by danamlewis** [comment]
"CoEpi wants to turn on Bluetooth: Bluetooth is used to anonymously detect the proximity of other devices." Would that work? or do we also need to include something like "Denying Bluetooth means that your CoEpi app will not be able to do exposure alerting."?

**Comment by haleybear** [comment]
> "CoEpi wants to turn on Bluetooth: Bluetooth is used to anonymously detect the proximity of other devices." Would that work? or do we also need to include something like "Denying Bluetooth means that your CoEpi app will not be able to do exposure alerting."?

Yes, I think that both lines would be helpful; however, if there is a way to add a secondary alert of the message "Denying Bluetooth means that your CoEpi app will not be able to do exposure alerting." it would keep the dialog at a manageable size.
The flow would then look like this: 

1. User has BT off (or turns BT off) and prompts the dialog: "CoEpi wants to turn on Bluetooth: Bluetooth is used to anonymously detect the proximity of other devices."  with Deny and Allow
2. User selects Deny and is prompted with a secondary verification of: "Denying Bluetooth means that your CoEpi app will not be able to do exposure alerting. Are you sure you would like to deny this permission?" with the options of "No, Go Back" (or something similar) and "I'm sure" 
3. User selects "No, Go Back" and the dialog closes either re-opening the permission dialog or uncovering it. 
--OR--
3. User selects "I'm sure" and the permission is denied.

**Comment by ivnsch** [comment]
Unless there are good reasons not to, I'd suggest that we stick to the flows recommended by Google. Here are the design guidelines for permissions: https://material.io/design/platform-guidance/android-permissions.html#usage

More technically oriented:
https://developer.android.com/training/permissions/usage-notes
https://developer.android.com/training/permissions/requesting#explain

IMO it would be ideal to provide context (as described in the design guidelines) via the onboarding. If they deny, we can provide a more exact one (as described in the technical docs) in a new dialog. Showing the user potentially 3 dialogs in a row (explanation, permission request, explanation again if they deny), in particular after they just went through the onboarding explanations, may be overwhelming.

Also, it has to be specified how to handle the case where the user confirms denying the permission, in which case the app (for its current purpose) would not be of use. This may change if the app is used too e.g. as a personal journal.
