### ISSUE TITLE
In android not getting the CEN key from IOS devices

### ISSUE THREAD

**Issue by Zuhadather** [Co-Epi/app-android#241]
Hi Team ,

I took the source code and I am trying to the scan from the iOS device.
I am not getting any key generated.
In BLEScanner class --> In scanResults
var contactEventIdentifier is coming us null if interacting with IOS device( when the app in foreground state itself ).
but the iOS device can get the key from android at the same time.

Any fix for this ? Please let me know.

**Comment by ivnsch** [comment]
There's no class named `BLEScanner` in this repo and the TCN client. There may have been in very early versions. What are you using?

**Comment by ivnsch** [comment]
I see now that you opened the same issue in the React Native repo. It's correct there. The implementation of this app is entirely different.

**Comment by Zuhadather** [comment]
> There's no class named `BLEScanner` in this repo and the TCN client. There may have been in very early versions. What are you using?

I have used the code of optimize_build branch.

Itseems that branch is deleted.

Just one Question : Is the updated branch works seamlessly on cross platform - I mean IOS and Android ?

**Comment by Zuhadather** [comment]
> I see now that you opened the same issue in the React Native repo. It's correct there. The implementation of this app is entirely different.

Wrongly updated there.

**Comment by i-schuetz** [comment]
The issue is wrong here. The React Native app is the other repo.
