### ISSUE TITLE
App Crashes Entering 11 Digits into Symptom Duration Field

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#243]
**Describe the bug**
When entering 11 digits (10000000000 used most often) into the Symptom Duration field on the "How many days have you been _______?" screen, the CoEpi application will crash.  This is repeatable for all symptoms.
-Device Details:
---Pixel 2 loaded with develop branch 0.3 (67) commit 22bfa86 on Android OS 10

**To Reproduce**
1. Select the Symptom Reporting button on the Home Screen.
2. Select any symptom on the list (will use Cough for this write-up) and select the SUBMIT button on the Symptom Report Screen.
3. Select Wet.
4. Enter 11 digits in the duration field and note the app crashes.

**Expected behavior**
The app should likely have an upper bounds applied to the duration field to avoid crashes.  What this value is could be determined via medical advice.  A quick upper bound could be 365, but something more COVID specific could also be 14 days (or whatever incubation period is of interest).  
**Making this value configurable for different illnesses would probably be a nice to have.

**Comment by ivnsch** [comment]
Thanks for the report! Yeah, defining meaningful upper/lower boundaries for all the inputs and how to enforce them is a still open task. For now at least (very quick fix) we could set a reasonable max chars count. @danamlewis

**Comment by SSNimnicht** [comment]
To your point @i-schuetz, I just noted that I can submit the Symptom Duration screen without entering a value in the days field.  I didn't use the skip button or the I don't know button, just selected SUBMIT and the App progressed to the next screen.  I look forward to learning about those boundaries to verify later.  Thanks!

**Comment by danamlewis** [comment]
Let's do max 2 digits/characters for days; since anything beyond that is out of scope/unlikely to be contagious for the transmissible diseases we care about. (If someone wants to argue for 3 digits, sure, but 2 seems reasonable, and we can always update in the future!). Allow 0-99, for example (where 0 = today, 1 = yesterday).  

Do we need to ask for UX guidance to prompt for invalid entries?

**Comment by ivnsch** [comment]
@Joshua-McCord This is fixed, right? If yes please close the issue.

**Comment by SSNimnicht** [comment]
@i-schuetz and @Joshua-McCord I pulled down commit af4a15fbfea483fd978ff79935107790d52e415a and am limited to 2 characters...no crash.
