### ISSUE TITLE
SUGGESTION:  Extraneous Screen in Cough and Fever Workflows

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#244]
Noted on a Pixel 2 with 0.3 (67) commit 22bfa86 on Android OS 10.

When entering in details about a Cough or Fever, the attached Extraneous Earliest Symptom Screen displays after the user has already entered duration information on the symptom specific Follow Up Duration Screen.  This flow is confusing (mainly it makes the user think his/her previous duration information wasn't understood/stored) and doesn't match the current flow documented on Figma.

Suggestion:  Remove this Extraneous screen for the Cough and Fever workflows.
 
![Extraneous_Earliest_Symptom_Screen](https://user-images.githubusercontent.com/67011880/84945187-f5a42a80-b0b4-11ea-8202-72db82b60bd1.png)

**Comment by ivnsch** [comment]
@danamlewis? IIUC It's about the repetition with the "How many days have you had a fever?" and "How many days have you been coughing?" screens. 

The most simple solution would be probably to remove the symptom-specific duration screens, which we don't need for 0.3/0.4 anyway.

**Comment by danamlewis** [comment]
Agreed - given that we are anchoring the symptom report from the earliest duration date, let's remove the symptom-specific duration screens from the flow for now.

**Comment by mellowgeek** [comment]
I went ahead and created a matching issue for this in the iOS repo.
