### ISSUE TITLE
Highest Temperature Today Screen Displays When User Said He/She Didn't Take It

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#248]
**Describe the bug**
After selecting No on the "Have you taken your temperature today?" screen, the app progresses to the "What was the highest temperature reading today?" screen.  This flow is pretty confusing and makes the user think the app didn't understand/store the information entered on the previous screen--even with the I don't know button available.
-Device Details:
---Pixel 2 loaded with develop branch 0.3 (67) commit 22bfa86 on Android OS 10

**To Reproduce**
1. Select Symptom Reporting button on Home Screen, select Fever button and SUBMIT button on Symptom Report Screen.
2. Enter 1 in days and SUBMIT button or select Skip or select I don't know button on Fever Duration Screen.
3. Select No button on the "Have you taken your temperature today?" Screen.
4. Error:  Extraneous highest temperature today screen displays.

**Expected behavior**
If the user selects they have not taken their temperature today the flow could skip the highest temperature today screen or could display a screen prompting the user to take their temperature then and record the value with the option to select "cannot currently measure".

**Comment by ivnsch** [comment]
I brought this up too, someone suggested removing the "Have you taken your temperature today?" screen, but AFAIR there has been no last word/issue on what to do / how to adapt the remaining screen.

**Comment by danamlewis** [comment]
After 'have you taken your temperature', a "no" response should then skip the remaining follow up screens (where you took it; highest temperature) and continue the rest of the symptom flow as needed.
