### ISSUE TITLE
TCN is not changing in Debug screen

### ISSUE THREAD

**Issue by woodsk97** [Co-Epi/app-android#256]
I thought TCN should be changing around every 15 minutes.  I've been bringing up Debug and don't see the TCN changing on that screen.  See attached for pictures of the Debug information.

![image](https://user-images.githubusercontent.com/67012738/85324586-1d6e0680-b498-11ea-9e2f-4e00856aa025.png)

**Comment by ivnsch** [comment]
Hmm, it _should_ work.

@Joshua-McCord Want to investigate this? The trigger is in the TCN library `ChangeOwnTcnAlarm` and `ChangeOwnTcnReceiver`.

**Comment by haleybear** [comment]
I set a timer to verify and my debug screens still show the old TCN as well. One phone I fully restarted after the 15 minutes and it shows the TCN as being the same both on the screen and within the Android Studio terminal debug.

**Comment by Joshua-McCord** [comment]
Yeah, I'll take a look at this!

**Comment by ivnsch** [comment]
Any update? Do we know at least if the timer is triggering?
