### ISSUE TITLE
Crash reporting in AppCenter

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-android#258]
- Missing steps in Diagnostics > Issues

**Comment by ivnsch** [comment]
Any updates? Github integration isn't needed (this probably would spam the board). Only that both AppCenter accounts shows them. Ideally we should use only one AppCenter account, but that's also not part of this task.

**Comment by mellowgeek** [comment]
@i-schuetz I don't think we can have the app report to both accounts. I added a branch with the new key if you want to switch crash reporting and telemetry to the new AppCenter account.

**Comment by ivnsch** [comment]
All the reports (develop and beta) are currently going to the old account?

**Comment by ivnsch** [comment]
But yeah, open a PR. Ideally we'd delete the old account, but if this is not possible we should move things out of it.

**Comment by mellowgeek** [comment]
Right, everything right now is still on the old account. PR opened, https://github.com/Co-Epi/app-android/pull/287
