### ISSUE TITLE
QUESTION: Inconsistencies on Android Symptom Reporting View

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-android#260]
I noticed a couple things that the most recent version of Android shows that are inconsistent with either Figma, iOS, or both:

- The view of the Symptom Report View currently does not match the Figma flow, but is very close to iOS, will it be adjusted again to be radio options or is this supposed to match iOS?

- Under "What symptoms do you have today?" Android currently says "Select one option" instead of "Select all that apply" even though the UI allows you to select multiple options

- Currently the option is "Breathless" on the application, "Breathlessness" on Figma, and "Short of breath" on iOS, but which one is correct?

- Currently the option is "I have symptoms that are not on the list" on the application, "Other" on Figma, and "Other" on iOS 

- The option for "I have symptoms that are not on the list" under the symptoms runs to the very edge of the bubble, if this verbiage is kept will the button be resized?

Current view on android:
![image](https://user-images.githubusercontent.com/36253327/85419031-91afb500-b53f-11ea-99d7-830d6e04fbb1.png)

**Comment by ivnsch** [comment]
@danamlewis @scottleibrand

**Comment by scottleibrand** [comment]
We should use "Select all that apply" and "Short of breath".

I think "I have symptoms that are not on the list" and "Other" are both clear: I'd be ok with whatever looks best.

I don't understand the radio button question.

**Comment by haleybear** [comment]
@scottleibrand : radio button was definitely the wrong term, sorry for that. 
Will the style be adjusted to match the Figma flow?
![image](https://user-images.githubusercontent.com/36253327/85798924-5b736080-b70c-11ea-9aa2-8930c7b1e48b.png)
Or will the Figma view be updated to reflect what the application has now

**Comment by danamlewis** [comment]
Thanks for flagging this - checking in with UX about the intended design and will follow up, original intent was for the apps to have matching experience so this new figma design of checkboxes was new to us as well.

**Comment by danamlewis** [comment]
Still not sure why Figma was changed, but after a quick check with dev and UX, we'll keep the current Android design (buttons, not checkboxes) to match the iOS experience for submitting symptoms.

see Scott's comments above for the other elements of this. Let's use "other" for the last button to not risk text wonkiness on different size screens.
