### ISSUE TITLE
Changing Screen Orientation while in CoEpi causes Location Permission Screen to Display

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#263]
**Describe the bug**
This issue was seen on a Pixel 2 with Android 10 loaded with develop branch commit af4a15f. When initially setting up the CoEpi app, I selected location permission while the application is open. With the CoEpi application open, when I rotate my screen from Portrait mode to Landscape (or from Landscape to Portrait mode) the "Allow CoEpi to access this device's location all the time?" pop-up displays...every time I rotate the phone.

**To Reproduce**
1. Open CoEpi.
2. Rotate screen from Portrait mode to Landscape (or from Landscape to Portrait mode).
3. The "Allow CoEpi to access this device's location all the time?" pop-up displays.
4. Tester selected Keep while-in-use access option and was still able to reproduce this behavior with each screen rotation.
---Note:  Keep and don't ask again stops pop-up display upon screen rotation.
5. Looking at the logs the user gets 12+ screens of "BLE preconditions not met" messages all with the same timestamp.  This appears to overwhelm the logs causing the user to lose insight into any other messages/functions/errors that may have occurred recently.

**Expected behavior**
Given the application has not been closed, this permission prompt should not appear.  This prompt should only appear upon re-opening the application.  

Additionally, the "BLE precondition not met" messages overwhelm the error log to the point where that is all the error log contains.  This may resolve if the screen rotation bug is fixed.

**Screenshots**
![Pop-up_Portrait_to_Landscape](https://user-images.githubusercontent.com/67011880/85444528-6a1d1480-b560-11ea-859e-b2736086a7cb.png)

![Pop-up_Landscape_to_Portrait](https://user-images.githubusercontent.com/67011880/85444536-6c7f6e80-b560-11ea-901e-198ca7e959ef.png)

Screen of 1 of 12+ with same timestamp and same error:
![Excessive_BLE_errors](https://user-images.githubusercontent.com/67011880/85444592-7b662100-b560-11ea-9d3c-7c620bc87cee.png)

**Comment by ivnsch** [comment]
Given that our layouts are not optimized for landscape (https://github.com/Co-Epi/app-android/issues/265) and we disabled this, this issue is irrelevant for now. Can be reopened if we ever decide to support landscape.
