### ISSUE TITLE
Rotating phone from portrait to landscape causes page overwrite/truncation

### ISSUE THREAD

**Issue by woodsk97** [Co-Epi/app-android#265]
Rotating phone from portrait to landscape causes overwrite/truncation of the current symptom screen.  Screenshots are from Samsung Galaxy S10 running CoEpi v0.3(77)

Steps to recreate:
1. Start CoEpi while phone is in portrait orientation
2. Select Symptom Report
3. Select Breathless then Submit  -- All options display correctly
![image](https://user-images.githubusercontent.com/67012738/85565734-69868b80-b5fd-11ea-9d5e-bccc178a59f9.png)

4.  Rotate the phone to landscape orientation - Header overwrites the options, not all options are visible and user can't scroll to access the complete list
![image](https://user-images.githubusercontent.com/67012738/85565780-730ff380-b5fd-11ea-8a09-7e7312d5c636.png)

Note:  On screens with fewer items, the header does not overwrite the selection but items are still trunctated - notice on the Fever follow-up screen, the 'Skip' option is not accessible
![image](https://user-images.githubusercontent.com/67012738/85567019-840d3480-b5fe-11ea-9112-89c2d79e271c.png)

**Comment by ivnsch** [comment]
@danamlewis Should we disable landscape for now?

**Comment by scottleibrand** [comment]
Yes, if we can prevent screen rotation entirely I think that'd be best.
