### ISSUE TITLE
Hightest temperature reading field only accepts 3 characters

### ISSUE THREAD

**Issue by woodsk97** [Co-Epi/app-android#266]
The input field on the 'What was the highest temperature reading today?' page only accepts 3 characters -- I used to be able to put in a temperature of 100.3, today I can only put in 100.  I have version 0.3(77) loaded on a Samsung Galaxy S10.

**Comment by scottleibrand** [comment]
This was limited in https://github.com/Co-Epi/app-android/pull/255 - we should probably increase the limit from 3 characters to 5? If we want to reduce precision when sending symptom reports, we should probably do the rounding after user entry, not force the user to round it.
