### ISSUE TITLE
Build 80 install issues

### ISSUE THREAD

**Issue by woodsk97** [Co-Epi/app-android#269]
I've tried to download and install build 80 and am having issues.
On the Android, when I try to open CoEpi, I get a message that the application keeps stopping.

**Comment by SSNimnicht** [comment]
Same here.

**Comment by ivnsch** [comment]
Please try again with the next build.

**Comment by ivnsch** [comment]
It will take a bit more to get this fixed. Please continue testing with the latest working build (77)

**Comment by ivnsch** [comment]
Build [84](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/build/branches/develop/builds/84) should work.
