### ISSUE TITLE
Fix java.lang.IllegalStateException in android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn (BluetoothLeUtils.java:136)

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#279]
### Reason ###

java.lang.IllegalStateException

### Link to App Center ###

* [https://appcenter.ms/users/danamlewis/apps/CoEpi-Android/crashes/errors/875495491u](https://appcenter.ms/users/danamlewis/apps/CoEpi-Android/crashes/errors/875495491u)

**Comment by ivnsch** [comment]
Opened an issue in the TCN library (I guess only for organization purpose, as we'll have to fix it).

**Comment by ivnsch** [comment]
https://github.com/TCNCoalition/tcn-client-android/issues/23
