### ISSUE TITLE
Wet Coughs Reported as Dry Coughs & Vice Versa

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#283]
**Describe the bug**
I logged a Wet Cough on my iPhone 7.  When I received the Exposure Alert on my Pixel 2, it cited the cough as Dry.  I later logged a Dry Couch on my iPhone 7 and the Exposure Alert on my Pixel 2 cited the cough as Wet.
Note:  Pixel 2 Android phone has OS 10 and Android commit 25909e5 [0.3 (90)] of the CoEpi App, 

**To Reproduce**
1. On iPhone log a Wet Cough.
2. Open the Exposure Alert on the Android phone and see that the Cough is logged as Dry.
<or>
3. On iPhone log a Dry Cough.
4. Open the Exposure Alert on the Android phone and see that the Cough is logged as Wet.

**Expected behavior**
A wet cough versus a dry cough should be reported on receiving phones correctly.

**Screenshots**
_Report submitting Wet Cough on iPhone_
![iOS_WetCough_Report](https://user-images.githubusercontent.com/67011880/85895616-05aebf00-b7c5-11ea-83a6-40b7251591e3.jpg)

_Exposure Report on Android for Wet Cough_
![And_Exposure_Alert_WetCough](https://user-images.githubusercontent.com/67011880/85895821-5de5c100-b7c5-11ea-89f2-a1706221aacf.png)

_Detailed Exposure Report on Android for Wet Cough_
![And_Detail_Exp_Alert_WetCough](https://user-images.githubusercontent.com/67011880/85895868-72c25480-b7c5-11ea-8045-248016a75118.png)

_Report submitting Dry Cough on iPhone_
![iOS_DryCough_Report](https://user-images.githubusercontent.com/67011880/85896004-af8e4b80-b7c5-11ea-9dfc-847cae937c4e.jpg)

_Exposure Report on Android for Dry Cough_
![And_Exposure_Alert_DryCough](https://user-images.githubusercontent.com/67011880/85895970-9e453f00-b7c5-11ea-9462-f7f8bd7ddb94.png)

_Detailed Exposure Report on Android for Dry Cough_
![And_Detail_Exp_Alert_DryCough](https://user-images.githubusercontent.com/67011880/85895932-91285000-b7c5-11ea-88df-a503c19bebda.png)

**Comment by ivnsch** [comment]
co-epi/app-backend-rust#110
