### ISSUE TITLE
Multiple Timestamps on Exposure Alert Can Cause Confusion

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#288]
**Describe the bug**
There are 2 different timestamps that display on Exposure Alerts where one of the timestamps is not explained at all.  This initially lead me to be confused about when the exposure happened.  After reviewing the debug logs, I believe I confirmed what the timestamps are, but a normal user won't have debug logs to decipher the timestamps. 

**To Reproduce**
1. Ensure your device has seen another device and logged that other device's TCN.
2. **SEVERAL MINUTES** later, register a symptom report on both devices.
3. Wait to receive the exposure alert.  The exposure alert notification on the 'list' screen shows a timestamp that I believe is the timestamp when the TCNs were exchanged. 
4. Select the exposure alert and the detailed exposure alert shows the "TCN exchange timestamp" again, but also a reported on timestamp.  These two different timestamps can be hours/days apart and confuse the user.

**Expected behavior**
An explanation of the "TCN exchange timestamp" would be helpful.  Perhaps a phrase like "Contact Timestamp" or the like.

**Screenshots**
![Misleading_Timestamp](https://user-images.githubusercontent.com/67011880/86156765-73642f00-bad4-11ea-8f21-e87399de0930.png)

![Multiple_Timestamps](https://user-images.githubusercontent.com/67011880/86156775-765f1f80-bad4-11ea-842f-63ed047fa110.png)

**Additional context**
These exposure alerts only registered on my Pixel 2 loaded with commit 25909e5 [0.3 (90)] on Android OS 10 because my iPhone 7 loaded with commit 90566b8 on iOS 13.5.1 didn't register any of my Android's exposures (which were identical to my iPhone's exposures).

**Comment by ivnsch** [comment]
We had this topic in Slack a while ago and agreed about it being confusing. @Co-Epi/ux

**Comment by danamlewis** [comment]
Resolved in subsequent designs now merged; closing.
