### ISSUE TITLE
Transitioning views intermittently flashes an inaccurate view on Android

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-android#290]
**Describe the bug**
On a new installation, the application flashes a view of the home screen that has "notifications" for symptom reporting and for exposure notifications before showing the current view (which has no new notifications). This is intermittent and the steps to reproduce the behavior are written to reflect that.

**To Reproduce**
1. Install application
2. Navigate to home screen
3. Select Exposure Alerts
4. Select back arrow
5. Select Exposure Alerts
6. Select back arrow
7. Observe that there is an extraneous view that appears during the view transition

**Expected behavior**
On transitioning from any screen to Home the view should not include the blank view.

**Screenshots**

Current Screen transitions (frame by frame from video capture of the device screen):

![image](https://user-images.githubusercontent.com/36253327/86167801-2f2d5a80-bae5-11ea-9532-512a9496962a.png)
![image](https://user-images.githubusercontent.com/36253327/86167817-35233b80-bae5-11ea-9191-f3dc9a335e19.png)
![image](https://user-images.githubusercontent.com/36253327/86167837-3ce2e000-bae5-11ea-83af-b766dd552545.png)

**Additional context**
Pixel 3XL 
Android 10
Current version: https://github.com/Co-Epi/app-android/tree/3eca05c60eaf889a26a178d41a3bfb0ab74e17b0/app

[Debug-Flashing-Screen.txt](https://github.com/Co-Epi/app-android/files/4854016/Debug-Flashing-Screen.txt)

**Comment by ivnsch** [comment]
I couldn't reproduce a noticeable delay. Only the red dots blinking shortly. This is fixed.
