### ISSUE TITLE
QUESTION: What is the purple dot on the application icon?

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-android#291]
On a new installation, the phone does not have exposure notifications and no symptoms have been reported - so what does this icon status mean? 
Is there a specific view of the application that explains this to users?
![image](https://user-images.githubusercontent.com/36253327/86169574-da3f1380-bae7-11ea-8064-63a9cd73ddfc.png)

**Comment by SSNimnicht** [comment]
Piling on with more pictures of similar issue on my Pixel 2 with commit 679cfca [0.3 (95)].

Icon displayed right after installing new version of application:
![No_Dot_Icon](https://user-images.githubusercontent.com/67011880/86170592-5c7c0780-bae9-11ea-9cb2-5707a98de762.png)

Icon displayed 2 hours after installing application and BEFORE receiving ANY exposure alerts (Had discovered iPhone TCN by now):
![Dot_Icon](https://user-images.githubusercontent.com/67011880/86170965-ee841000-bae9-11ea-83cb-1831d95dda05.png)

Also note:  AFTER receiving several exposure alerts, the dot remained purple.
![Exposure_Alert_Active](https://user-images.githubusercontent.com/67011880/86171345-926dbb80-baea-11ea-8923-e94a4abe979c.png)

![Purple_Dot_with_Active_Exposure](https://user-images.githubusercontent.com/67011880/86171353-9568ac00-baea-11ea-9067-b391c01fd0c6.png)

**Comment by i-schuetz** [comment]
The badge should show only while there's an active OS notification. It's not directly related with the in-app alerts. From your status bar it doesn't look like you have any, but can you confirm?

Also, the situation where there's an OS notification but no alerts in the app _shouldn't_ be possible, as it was recently implemented to clear the OS notifications when opening the alerts screen @laurenipsum365

**Comment by ivnsch** [comment]
Can you long-press the app icon to see what the notification is?

**Comment by ivnsch** [comment]
To be clear, the dot shows when there's an active OS notification (which you can see either long-tapping the icon, or pulling down the notification bar (top bar). We trigger OS notifications when we receive new alerts. The OS notifications are dismissed when opening the alert screen (and with that the dot should disappear). There shouldn't be new notifications directly after app installation (without having opened the app and given the permissions).

**Comment by haleybear** [comment]
@i-schuetz it looks like it's an on-going notification for the fact that it's running.
With that information readily available in the notification bar, is it intentional to have this be a constant? 
![image](https://user-images.githubusercontent.com/36253327/86186773-eb981800-bb07-11ea-977e-057d907fbf16.png)
Also, when the phone is restarted and the application is still available (swiping up on the bottom nav shows it as an option) when would you expect to see it start running again? Would we need to open it again or should it auto-start if the window is available?
![image](https://user-images.githubusercontent.com/36253327/86186976-a88a7480-bb08-11ea-9912-588b6affa1e2.png)
![image](https://user-images.githubusercontent.com/36253327/86186987-b0e2af80-bb08-11ea-956c-3621bb6ac292.png)

**Comment by ivnsch** [comment]
Ah right, the TCN service shows this permanent notification. The badge can be disabled.
