### ISSUE TITLE
Android Fever Workflow doesn’t match iOS Workflow or Figma

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#293]
**Describe the bug**
When going through the Fever workflow on an iPhone and an Android phone side by side, the user will notice that the Android workflow does not match the iOS workflow or what appears to be THE Figma workflow.  Android Phone details:  Pixel 2 with Android OS 10 loaded with CoEpi Android commit 679cfca [0.3 (95)]

**To Reproduce**
1. Select Fever as the only symptom.
2. Step through the workflow on an Android phone and an iPhone.  They will switch ordering after selecting Yes or No on the "Have you taken your temperature today?" screen and will not sync back up until the "How many days ago did the symptoms begin?" screen.

**Expected behavior**
The Android workflow should match the iOS workflow which appears to match Figma.

**Screenshots**
Flow3 is where they diverge, Flow6 is where they sync back up

![And_Fever_Flow1](https://user-images.githubusercontent.com/67011880/86176784-7cb0c400-baf3-11ea-810c-ba0d720e532b.png)
![And_Fever_Flow2](https://user-images.githubusercontent.com/67011880/86176786-7d495a80-baf3-11ea-84d4-02dd7c45cecb.png)
![And_Fever_Flow3](https://user-images.githubusercontent.com/67011880/86176788-7d495a80-baf3-11ea-99ec-1075da3536b8.png)
![And_Fever_Flow4](https://user-images.githubusercontent.com/67011880/86176789-7de1f100-baf3-11ea-85a6-d594ae22f5be.png)
![And_Fever_Flow5](https://user-images.githubusercontent.com/67011880/86176790-7e7a8780-baf3-11ea-887a-04885f1bd106.png)
![And_Fever_Flow6](https://user-images.githubusercontent.com/67011880/86176791-7e7a8780-baf3-11ea-9a1a-048c5725f752.png)
![And_Fever_Flow7](https://user-images.githubusercontent.com/67011880/86176792-7e7a8780-baf3-11ea-9efd-f2754f62b69c.png)

**Comment by ivnsch** [comment]
To me the Android flow seems more natural, "Have you taken your temperature _today_"?, > "What was the highest temperature reading _today_?. In figma there's "Where did you take your temperature most recently?" in the middle, which interrupts the "today" flow. @Co-Epi/ux

**Comment by danamlewis** [comment]
Resolved in subsequent versions; closing.
