### ISSUE TITLE
Various UI Inconsistencies Between Android and iOS

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#296]
**Describe the bug**
See attached Word document for specific screens that have discrepancies between Android and iOS (big and small).
[UI Inconsistencies.docx](https://github.com/Co-Epi/app-android/files/4854497/UI.Inconsistencies.docx)

**To Reproduce**
Screens to view the divergent behavior:
1. Onboarding Screen #4
2. Shortness of Breath Follow Up Screen
3. Cough Level Screen
4. Symptom Report Thank You Screen

**Expected behavior**
UI Consistency between Android and iOS as much as possible

**Comment by ivnsch** [comment]
UI consistency isn't really a goal. Often designs are vastly different between platforms and, in general, nobody checks that e.g. translations are identical.

That said, most of these issues are bugs on their own (e.g. there shouldn't be a space in the onboarding text) and will be addressed.

**Comment by haskinselena** [comment]
We just finished user testing and the copywriter will be making updates to everything. I'll let you know when those are ready  and then the ios and Android should be the same afterwards.
