### ISSUE TITLE
Fix kotlin.TypeCastException in org.tcncoalition.tcnclient.receiver.ChangeOwnTcnReceiver.onReceive (ChangeOwnTcnReceiver.kt:24)

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#297]
### Reason ###

kotlin.TypeCastException

### Link to App Center ###

* [https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/232441117u](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/232441117u)

**Comment by ivnsch** [comment]
Hmm this seems to come from my device, while I was fixing the timer bug. Don't remember seeing the crash. Line is outdated now. Let's observe it.

We shouldn't be sending development crashes to AppCenter, btw (though in this case it may be accidentally helpful).
