### ISSUE TITLE
On-board screens

### ISSUE THREAD

**Issue by haskinselena** [Co-Epi/app-android#313]
1. Add opening screen
2. Update copy
3. Add visuals

<img width="1049" alt="Screen Shot 2020-07-21 at 10 52 30 PM" src="https://user-images.githubusercontent.com/67452742/88128939-ea0cbd80-cba4-11ea-97d4-8382ac1ecf8f.png">

**Comment by ivnsch** [comment]
@haskinselena Could you please cut the images such that the bottom is exactly at the top of the card and they can be exported respectively as a unit? When exporting for iOS I had to do adjustments per image in the app and this is not good...

**Comment by haskinselena** [comment]
I'll do this first thing in the morning. Do you want me also upload the svg zip for you? Or just add to figma

**Comment by ivnsch** [comment]
Figma is ok. Though exporting could be helpful if you want to double-check that it's correct.

**Comment by haskinselena** [comment]
They're updated in Figma - and here
[slide_illustrations.zip](https://github.com/Co-Epi/app-android/files/5041546/slide_illustrations.zip)
