### ISSUE TITLE
Fix java.util.UnknownFormatConversionException in org.coepi.android.di.ModulesKt$viewModelModule$1$11.invoke

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#315]
### Reason ###

java.util.UnknownFormatConversionException

### Link to App Center ###

* [https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/1104206691u](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/1104206691u)

**Comment by ivnsch** [comment]
These crashes shouldn't be sent to AppCenter. https://github.com/Co-Epi/app-android/issues/318
