### ISSUE TITLE
Fix java.lang.IllegalArgumentException in org.coepi.android.di.ModulesKt$viewModelModule$1$11.invoke

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#316]
### Reason ###

java.lang.IllegalArgumentException

### Link to App Center ###

* [https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/1869272586u](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/1869272586u)

**Comment by ivnsch** [comment]
These crashes shouldn't be sent to AppCenter. https://github.com/Co-Epi/app-android/issues/318
