### ISSUE TITLE
Fix java.util.MissingFormatArgumentException in org.coepi.android.di.ModulesKt$viewModelModule$1$11.invoke

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#317]
### Reason ###

java.util.MissingFormatArgumentException

### Link to App Center ###

* [https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/220722462u](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/220722462u)

**Comment by ivnsch** [comment]
These crashes shouldn't be sent to AppCenter. https://github.com/Co-Epi/app-android/issues/318
