### ISSUE TITLE
Fix android.util.AndroidRuntimeException in android.app.ContextImpl.startActivity (ContextImpl.java:952)

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#335]
### Reason ###

android.util.AndroidRuntimeException

### Link to App Center ###

* [https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/3593207459u](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/3593207459u)

**Comment by ivnsch** [comment]
These crashes shouldn't be sent to AppCenter. #318
