### ISSUE TITLE
Fix java.lang.ClassNotFoundException in androidx.fragment.app.FragmentFactory.loadClass (FragmentFactory.java:47)

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#336]
### Stacktrace ###

androidx.fragment.app.FragmentFactory.loadClass (FragmentFactory.java:47);

androidx.fragment.app.FragmentFactory.loadFragmentClass (FragmentFactory.java:88);

androidx.fragment.app.Fragment.instantiate (Fragment.java:546);

androidx.fragment.app.FragmentContainer.instantiate (FragmentContainer.java:57);

androidx.fragment.app.FragmentManager$3.instantiate (FragmentManager.java:390);

androidx.navigation.fragment.FragmentNavigator.instantiateFragment (FragmentNavigator.java:132);

androidx.navigation.fragment.FragmentNavigator.navigate (FragmentNavigator.java:162);

androidx.navigation.fragment.FragmentNavigator.navigate (FragmentNavigator.java:58);

androidx.navigation.NavController.navigate (NavController.java:1049);

androidx.navigation.NavController.navigate (NavController.java:935);

androidx.navigation.NavController.navigate (NavController.java:868);

androidx.navigation.NavController.navigate (NavController.java:854);

androidx.navigation.NavController.navigate (NavController.java:1107);

io.reactivex.internal.observers.LambdaObserver.onNext (LambdaObserver.java:63);

io.reactivex.subjects.PublishSubject$PublishDisposable.onNext (PublishSubject.java:308);

io.reactivex.subjects.PublishSubject.onNext (PublishSubject.java:228);

org.coepi.android.databinding.FragmentHomeBindingImpl._internalCallbackOnClick (FragmentHomeBindingImpl.java:171);

org.coepi.android.generated.callback.OnClickListener.onClick (OnClickListener.java:11);

### Reason ###

java.lang.ClassNotFoundException

### Link to App Center ###

* [https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/3843526507u](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/3843526507u)

**Comment by ivnsch** [comment]
These crashes shouldn't be sent to AppCenter. #318
