### ISSUE TITLE
Fix java.lang.IllegalStateException: Symptom flow not set in androidx.activity.OnBackPressedDispatcher.onBackPressed (OnBackPressedDispatcher.java:192)

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#351]
### Stacktrace ###

androidx.activity.OnBackPressedDispatcher.onBackPressed (OnBackPressedDispatcher.java:192);

androidx.activity.ComponentActivity.onBackPressed (ComponentActivity.java:314);

androidx.core.app.ComponentActivity.superDispatchKeyEvent (ComponentActivity.java:122);

androidx.core.view.KeyEventDispatcher.dispatchKeyEvent (KeyEventDispatcher.java:84);

androidx.core.app.ComponentActivity.dispatchKeyEvent (ComponentActivity.java:140);

androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent (AppCompatActivity.java:558);

androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent (WindowCallbackWrapper.java:59);

androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent (AppCompatDelegateImpl.java:2814);

### Reason ###

java.lang.IllegalStateException: Symptom flow not set

### Link to App Center ###

* [https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/935782454u](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/crashes/errors/935782454u)

**Comment by duskoo** [comment]
It an old build: 
[Version 0.3 (92)
Jul 21, 2020, 10:16 PM](https://appcenter.ms/users/danamlewis/apps/CoEpi-Android/distribute/releases/65)

Crash happens in EarliestSymptomFragment which is not used in newer builds of the app. 
I suggest closing the ticket.
