### ISSUE TITLE
Trying to get in touch

### ISSUE THREAD

**Issue by Rnorback** [Co-Epi/app-android#8]
Hi Dana and Scott,

Hope you’re well.

I have a team of highly skilled developers in Native Mobile on iOS and Android, as well as Backend and System Architects waiting in the wings ready to build out a Contact Tracer system.

Do you have some time to talk today or tomorrow? I’m on PST. My email is Rnorback [@] gmail.com.

Best,
Rob Norback

**Comment by scottleibrand** [comment]
Thanks for reaching out and joining our call. Looking forward to working with you.
